package Interfaz;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conexiones.conectar;


public class JFR_Login extends javax.swing.JFrame {

    conectar cc = new conectar();
    Connection cn = cc.conexion();

    /**
     * Creates new form JFR_Login
     */
    public JFR_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        TXT_Usuario.requestFocus();
    }

    void acceder(String usuario, String pass) {
        boolean existente = false;
        String tipo = "";
        String sql = "SELECT * FROM usuarios WHERE nick='" + usuario + "' && contraseña='" + pass + "'";
        
        try 
        {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
                        
            while(rs.next())
            {
               existente = true; 
               tipo = rs.getString("tipo");
            }
            
            if(existente == false)  //comprobar si no existe la cuenta
            {
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos", "Datos no validos", JOptionPane.ERROR_MESSAGE);
            }
            else if(tipo.equals("administrador"))
            {
                JOptionPane.showMessageDialog(null, "Bienvenido "+usuario, "Datos Correctos", JOptionPane.INFORMATION_MESSAGE);
                JFR_Principal pr = new JFR_Principal();
                pr.setVisible(true);
                pr.us.setText(usuario);
                this.dispose();
            }
            else if(tipo.equals("empleado"))
            {
                JOptionPane.showMessageDialog(null, "Bienvenido "+usuario, "Datos Correctos", JOptionPane.INFORMATION_MESSAGE);
                JFR_Principal pr = new JFR_Principal();
                pr.setVisible(true);
                pr.us.setText(usuario);
                this.dispose();
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(JFR_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Icono = new javax.swing.JLabel();
        BTN_Cerrar = new javax.swing.JButton();
        JL_Usuario = new javax.swing.JLabel();
        TXT_Usuario = new javax.swing.JTextField();
        JL_Contraseña = new javax.swing.JLabel();
        PSW_Contraseña = new javax.swing.JPasswordField();
        BTN_Entrar = new javax.swing.JButton();
        JL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        getContentPane().add(JL_Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        BTN_Cerrar.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        BTN_Cerrar.setText("Salir");
        BTN_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        JL_Usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        JL_Usuario.setText("Usuario:");
        getContentPane().add(JL_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 20));

        TXT_Usuario.setBackground(new java.awt.Color(153, 153, 153));
        TXT_Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TXT_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXT_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 190, -1));

        JL_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        JL_Contraseña.setText("Contraseña:");
        getContentPane().add(JL_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        PSW_Contraseña.setBackground(new java.awt.Color(153, 153, 153));
        PSW_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PSW_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PSW_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, -1));

        BTN_Entrar.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Entrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login_1.png"))); // NOI18N
        BTN_Entrar.setText("Entrar");
        BTN_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-web-gris.jpg"))); // NOI18N
        getContentPane().add(JL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_CerrarActionPerformed

    private void BTN_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EntrarActionPerformed
        String usu = TXT_Usuario.getText();
        String pas = new String(PSW_Contraseña.getPassword());
          if(usu.equals("")&& pas.equals("")){
             JOptionPane.showMessageDialog(null, "Ingrese sus Datos de Acceso");
          }else if(usu.equals("")){
              JOptionPane.showMessageDialog(null, "Ingrese su Usuario");
          }else if (pas.equals("")){
              JOptionPane.showMessageDialog(null, "Ingrese su Contraseña");
          }
         else{
        acceder(usu, pas);
        }
    }//GEN-LAST:event_BTN_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFR_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFR_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFR_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFR_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFR_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Entrar;
    private javax.swing.JLabel JL_Contraseña;
    private javax.swing.JLabel JL_Fondo;
    private javax.swing.JLabel JL_Icono;
    private javax.swing.JLabel JL_Usuario;
    private javax.swing.JPasswordField PSW_Contraseña;
    private javax.swing.JTextField TXT_Usuario;
    // End of variables declaration//GEN-END:variables
}
