/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexiones.conectar;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/*
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
*/

public class JFR_Principal extends javax.swing.JFrame {

    final JFR_Principal princ; //declaramos variable de esta clase
    
    public JFR_Principal() {
        initComponents();
        //System.out.println(this.getSize());
       //this.setSize(1000, 640);
        fecha.setText(fechaactual());
        this.setExtendedState(MAXIMIZED_BOTH);
        // this.setLocationRelativeTo(null);
            
        princ = this; //le pasamos ESTA MISMA CLASE a la variable (para mandarla a JIFR_Compras)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titu = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Escritorio = new javax.swing.JDesktopPane();
        fecha = new javax.swing.JLabel();
        BTN_Motos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BTN_Clientes = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_Inicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JM_Motocicletas = new javax.swing.JMenu();
        Item_adminMotos = new javax.swing.JMenuItem();
        JM_Clientes = new javax.swing.JMenu();
        item_AdminCli = new javax.swing.JMenuItem();
        JM_Servicios = new javax.swing.JMenu();
        item_AdminServ = new javax.swing.JMenuItem();
        JM_Rerparaciones = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        JM_Inventarios = new javax.swing.JMenu();
        item_AdminInv = new javax.swing.JMenuItem();
        JM_Ventas = new javax.swing.JMenu();
        JM_Proveedores = new javax.swing.JMenu();
        item_AdminProv = new javax.swing.JMenuItem();
        JM_Compras = new javax.swing.JMenu();
        JM_Facturacion = new javax.swing.JMenu();
        JM_Reportes = new javax.swing.JMenu();
        JM_Egresos = new javax.swing.JMenu();
        Empleados = new javax.swing.JMenuItem();
        JM_Ingresos = new javax.swing.JMenu();
        JM_Herramientas = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        JM_Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Administrador");
        setBackground(new java.awt.Color(0, 0, 0));

        titu.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        titu.setText("Usuario Conectado:");

        us.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N

        Escritorio.setPreferredSize(this.getSize());

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Escritorio);

        fecha.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        fecha.setText("jLabel2");

        BTN_Motos.setBackground(new java.awt.Color(0, 0, 0));
        BTN_Motos.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Motos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moto.png"))); // NOI18N
        BTN_Motos.setText("Motos");
        BTN_Motos.setPreferredSize(new java.awt.Dimension(140, 72));
        BTN_Motos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MotosActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/repair64.png"))); // NOI18N
        jButton1.setText("Reparaciones");
        jButton1.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTN_Clientes.setBackground(new java.awt.Color(0, 0, 0));
        BTN_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_customer_64.png"))); // NOI18N
        BTN_Clientes.setText("Clientes");
        BTN_Clientes.setPreferredSize(new java.awt.Dimension(140, 72));
        BTN_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ClientesActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/serv64.png"))); // NOI18N
        jButton3.setText("Servicios");
        jButton3.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shopping_cart_64.png"))); // NOI18N
        jButton4.setText("Compras");
        jButton4.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sales_64.png"))); // NOI18N
        jButton5.setText("Ventas");
        jButton5.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/truck_64.png"))); // NOI18N
        jButton6.setText("Proveedor");
        jButton6.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/report64.png"))); // NOI18N
        jButton7.setText("Reportes");
        jButton7.setPreferredSize(new java.awt.Dimension(140, 72));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(367, 40));

        JM_Inicio.setBackground(new java.awt.Color(0, 0, 0));
        JM_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/roadside_shop_24.png"))); // NOI18N
        JM_Inicio.setText("Inicio");

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JM_Inicio.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JM_Inicio.add(jMenuItem2);

        jMenuBar1.add(JM_Inicio);

        JM_Motocicletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Motorcycle24.png"))); // NOI18N
        JM_Motocicletas.setText("Motocicletas");

        Item_adminMotos.setText("Administrar");
        Item_adminMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_adminMotosActionPerformed(evt);
            }
        });
        JM_Motocicletas.add(Item_adminMotos);

        jMenuBar1.add(JM_Motocicletas);

        JM_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_customer_24.png"))); // NOI18N
        JM_Clientes.setText("Clientes");

        item_AdminCli.setText("Administrar");
        item_AdminCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_AdminCliActionPerformed(evt);
            }
        });
        JM_Clientes.add(item_AdminCli);

        jMenuBar1.add(JM_Clientes);

        JM_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/serv24.png"))); // NOI18N
        JM_Servicios.setText("Servicios");

        item_AdminServ.setText("Administrar");
        item_AdminServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_AdminServActionPerformed(evt);
            }
        });
        JM_Servicios.add(item_AdminServ);

        jMenuBar1.add(JM_Servicios);

        JM_Rerparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/settings_24.png"))); // NOI18N
        JM_Rerparaciones.setText("Reparaciones");

        jMenuItem7.setText("Administrar");
        JM_Rerparaciones.add(jMenuItem7);

        jMenuBar1.add(JM_Rerparaciones);

        JM_Inventarios.setBackground(new java.awt.Color(0, 0, 0));
        JM_Inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/packing_24.png"))); // NOI18N
        JM_Inventarios.setText("Inventario");

        item_AdminInv.setText("Administrar");
        item_AdminInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_AdminInvActionPerformed(evt);
            }
        });
        JM_Inventarios.add(item_AdminInv);

        jMenuBar1.add(JM_Inventarios);

        JM_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sales_24.png"))); // NOI18N
        JM_Ventas.setText("Ventas");
        jMenuBar1.add(JM_Ventas);

        JM_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/truck_24.png"))); // NOI18N
        JM_Proveedores.setText("Proveedores");

        item_AdminProv.setText("Administrar");
        item_AdminProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_AdminProvActionPerformed(evt);
            }
        });
        JM_Proveedores.add(item_AdminProv);

        jMenuBar1.add(JM_Proveedores);

        JM_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shopping_cart_24.png"))); // NOI18N
        JM_Compras.setText("Compras");
        jMenuBar1.add(JM_Compras);

        JM_Facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/invoice_24.png"))); // NOI18N
        JM_Facturacion.setText("Facturación");
        jMenuBar1.add(JM_Facturacion);

        JM_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/repair24.png"))); // NOI18N
        JM_Reportes.setText("Reportes");
        jMenuBar1.add(JM_Reportes);

        JM_Egresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gasto24.png"))); // NOI18N
        JM_Egresos.setText("Empleados");

        Empleados.setText("Administrar");
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        JM_Egresos.add(Empleados);

        jMenuBar1.add(JM_Egresos);

        JM_Ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Income24.png"))); // NOI18N
        JM_Ingresos.setText("Ingresos");
        jMenuBar1.add(JM_Ingresos);

        JM_Herramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tools24.png"))); // NOI18N
        JM_Herramientas.setText("Herramientas");

        jMenuItem11.setText("Respaldar Base de Datos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        JM_Herramientas.add(jMenuItem11);

        jMenuItem10.setText("Restaurar Base de Datos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        JM_Herramientas.add(jMenuItem10);

        jMenuItem9.setText("Administrar Usuarios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        JM_Herramientas.add(jMenuItem9);

        jMenuBar1.add(JM_Herramientas);

        JM_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help_24.png"))); // NOI18N
        JM_Ayuda.setText("Ayuda");
        jMenuBar1.add(JM_Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTN_Motos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BTN_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(titu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(737, 737, 737)
                .addComponent(fecha))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(160, 160, 160)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BTN_Motos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(BTN_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha)
                    .addComponent(titu)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFR_Login prn = new JFR_Login();
        prn.setVisible(true);
        // prn.pack();
        this.dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Seguro que quieres salir?");
        if (JOptionPane.OK_OPTION == resp) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void item_AdminInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_AdminInvActionPerformed
       JIFR_Inventario inv = new JIFR_Inventario();
        Escritorio.add(inv);
        inv.show();
        
        /*
        String utif = us.getText();
        String ftif = fecha.getText();
        Ingreso ing = new Ingreso(utif, ftif);
        Escritorio.add(ing);
        ing.show();
          */
    }//GEN-LAST:event_item_AdminInvActionPerformed

    private void Item_adminMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_adminMotosActionPerformed
        JIFR_Motos mot = new JIFR_Motos();
        Escritorio.add(mot);
        mot.show();
    }//GEN-LAST:event_Item_adminMotosActionPerformed

    private void BTN_MotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MotosActionPerformed

        JIFR_Motos mot = new JIFR_Motos();
        Escritorio.add(mot);
        mot.show();
        
    }//GEN-LAST:event_BTN_MotosActionPerformed

    private void BTN_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ClientesActionPerformed
     JIFR_Clientes cli=new JIFR_Clientes();
    
     //Damos MEDIDAS para poner ScrollPane (barra de dezplazamiento) al Escritoio
//Escritorio.setPreferredSize(new Dimension(cli.getWidth(), cli.getHeight()));
    //comentamos para bloquear scrollpane del Escritorio ya que pusimos a cada Frame su Scroll

    Escritorio.add(cli);
     cli.show();
    }//GEN-LAST:event_BTN_ClientesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
      JIFR_Servicios servi = new JIFR_Servicios();
        Escritorio.add(servi);
        servi.show();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JIFR_Ventas ven = new JIFR_Ventas();
        Escritorio.add(ven);
        ven.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        JIFR_Proveedores prv = new JIFR_Proveedores();
        Escritorio.add(prv);
        prv.show();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JIFR_Compras com = new JIFR_Compras(princ);
        Escritorio.add(com);
        com.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     /*
        DEUDAS DEU = new DEUDAS();
        Escritorio.add(DEU);
        DEU.show();
        */
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void item_AdminProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_AdminProvActionPerformed
        JIFR_Proveedores PROV = new JIFR_Proveedores();
        Escritorio.add(PROV);
        PROV.show();
    }//GEN-LAST:event_item_AdminProvActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        JIFR_Empleados  em= new JIFR_Empleados();
        Escritorio.add(em);
        em.show();
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void item_AdminCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_AdminCliActionPerformed
        JIFR_Clientes cli = new JIFR_Clientes();
        Escritorio.add(cli);
        cli.show();
    }//GEN-LAST:event_item_AdminCliActionPerformed

    private void item_AdminServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_AdminServActionPerformed
        JIFR_Servicios serv = new JIFR_Servicios();
        Escritorio.add(serv);
        serv.show();
    }//GEN-LAST:event_item_AdminServActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JIFR_Reparaciones rep = new JIFR_Reparaciones();
        Escritorio.add(rep);
        rep.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JIFR_Usuarios us = new JIFR_Usuarios();
        Escritorio.add(us);
        us.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JIFR_RespaldarBD resp = new JIFR_RespaldarBD();
        Escritorio.add(resp);
        resp.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JIFR_RestaurarBD res = new JIFR_RestaurarBD();
        Escritorio.add(res);
        res.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFR_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFR_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFR_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFR_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFR_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Clientes;
    private javax.swing.JButton BTN_Motos;
    private javax.swing.JMenuItem Empleados;
    public javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem Item_adminMotos;
    private javax.swing.JMenu JM_Ayuda;
    private javax.swing.JMenu JM_Clientes;
    private javax.swing.JMenu JM_Compras;
    private javax.swing.JMenu JM_Egresos;
    private javax.swing.JMenu JM_Facturacion;
    private javax.swing.JMenu JM_Herramientas;
    private javax.swing.JMenu JM_Ingresos;
    private javax.swing.JMenu JM_Inicio;
    private javax.swing.JMenu JM_Inventarios;
    private javax.swing.JMenu JM_Motocicletas;
    private javax.swing.JMenu JM_Proveedores;
    private javax.swing.JMenu JM_Reportes;
    private javax.swing.JMenu JM_Rerparaciones;
    private javax.swing.JMenu JM_Servicios;
    private javax.swing.JMenu JM_Ventas;
    private javax.swing.JLabel fecha;
    private javax.swing.JMenuItem item_AdminCli;
    private javax.swing.JMenuItem item_AdminInv;
    private javax.swing.JMenuItem item_AdminProv;
    private javax.swing.JMenuItem item_AdminServ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titu;
    public static javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}
